GET http://localhost:3001/api/service-providers/3 HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjg1MzMxOTIzLCJleHAiOjE2ODU0MTgzMjN9.WK2kfyeVLmmpzSZeY7927NrW6crMWNjzS7JrIKh300A

###