GET http://localhost:3001/api/services HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksImlhdCI6MTY4NTAyNjYxMCwiZXhwIjoxNjg1MTEzMDEwfQ.F9h7tZIz4Z94ykUWT81WqZImQIWTeFDskpxVhpPv1Hs

###
